### ISSUE TITLE
bash: make: command not found

### ISSUE THREAD

**Issue by bobbyshaw** [lorisleiva/laravel-docker#101]
Similar to #96 #98 and #100, running pipelines today that had previously succeeded failed with:

```
bash: make: command not found
````

Thanks for your work on this image 🙌

**Comment by lorisleiva** [comment]
Hi there 👋 

Sorry about that, this is due to a refactoring PR that refactored a bit too much. 😬 

I've just pushed [a new commit](https://github.com/lorisleiva/laravel-docker/commit/c28a58a911c9778382b593391b11c52222cbaf7d) that should fix this issue once the images are built and deployed. I'll close this in the meantime but let me know if the error persists and I'll reopen it. 🙂
