### ISSUE TITLE
[Vote] Add hirak/prestissimo to speed up installs

### ISSUE THREAD

**Issue by tranba** [lorisleiva/laravel-docker#11]
I think, we can add the [hirak/prestissimo](https://github.com/hirak/prestissimo) to speed up composer installs

**Comment by lorisleiva** [comment]
Hi there 👋 

Sorry about the late reply, I was just observing whether this addition would get some upvote.

I'm trying to keep this generic image as small as possible whist covering 80% of Laravel use cases.

I'm going to leave this issue open and let people vote with thumbs up. If I see that this is popular and necessary for most projects, I'll add it to this DockerFile. Otherwise it is difficult for me to draw the line.

In the meantime you can fork this repository and upload your own DockerFile to [Docker Hub](https://hub.docker.com/).

**Comment by JustPlayerDE** [comment]
When using composer 2 [hirak/prestissimo](https://github.com/hirak/prestissimo) is not required anymore (and is not working anyways)

**Comment by lorisleiva** [comment]
Agreed, it’s now obsolete for composer 2. Let’s close this. ☺️
