### ISSUE TITLE
Potential memory issues with 7.4

### ISSUE THREAD

**Issue by ragingdave** [lorisleiva/laravel-docker#49]
**Note that this issue was original created to fix some missing dependencies of the new `7.4` image. [Scroll down](#issuecomment-573970831) for the memory issue.**

_Original post below:_

---

I'm not sure what exactly was including it but previous docker images had the exif extension as I am now getting (without any package changes between the last successful build and now):

`
    - Installation request for spatie/image 1.7.5 -> satisfiable by spatie/image[1.7.5].
    - spatie/image 1.7.5 requires ext-exif * -> the requested PHP extension exif is missing from your system.
`

The last successful build in the same repo was Jan 10, 2020 at 11AM EST. This is causing our pipeline to effectively die for no good reason other than a docker build image update. I unfortunately can't share much more than this as it's a private company repo. Additionally I looked the changes in the docker image for php7.3 (stable) and it seems nothing changed there.

Small update as I was writing this, it seems (based on looking at the compressed sizes on docker hub) that stable was replaced last night for 7.4. This seems to break most builds that were using stable and IMHO flies in the face of what "stable" even means. Would you be able to add back exif (as it previously was/is there in the 7.3 build) to the 7.4 build or perhaps just swap stable back to 7.3 until your 7.4 docker image has feature/extension parity with 7.3? This is basically nuking our pipeline right now and appears to have been an overnight change without any announcements to prepare.

**Comment by lorisleiva** [comment]
Hi there 👋

Thank you for raising this!

That is very strange indeed. I've looked at the PHP 7.4 changelog and `diff`ed the official alpine Dockerfile for `7.3` and `7.4` and there is nothing mentioned about unbundling `exif` by default.

In any case, I have now explicitly added it for `7.4`. I've checked that locally by successfully running `php -m | grep exif` inside a freshly built container (whereas it wasn't returning anything prior to my last commit so you're 100% right).

A quick note on using `stable` in your CI: It might be a good idea to use specific versions like `7.3` and then switch to `7.4` whenever your codebase is ready. Otherwise, you might always be the first one to get all the issues when new PHP versions become available. That being said, it is very useful for me to debug haha.

Anyways, this should be all fixed now (as soon as Docker Hub finishes building the images).

**Comment by ragingdave** [comment]
So that seems to have improved it, however I am hitting another issue that was previously fixed now:

`Error: Call to undefined function easter_days()` which I believe ends up being solved via the calendar extension. #44

**Comment by kreitje** [comment]
I was getting the exif error from the scheduled job that is now cleared up after the update.

_Side note:  With :latest I am getting errors about memory exhausted on GitLab CI and downgrading to 7.3 solved it._

**Comment by lorisleiva** [comment]
@ragingdave Yep, `calendar` was missing from the `7.4` image, I've added it back.

@kreitje Thank you for letting me know. Do you have any idea what was using too many resources? I've decided to support JPEG for the GD extension on `7.4` but I should probably revert this if it's going to be too heavy on CI pipelines.

**Comment by ragingdave** [comment]
From at least 2 of my repos things appear all good (they are the most complex of my current CI stuff) so I would say things are good from my end. Can't say one way or the other from the jpeg support as my builds don't seem to complain about that in 7.4

**Comment by kreitje** [comment]
The 2 spots where it ran out of memory on Gitlab CI was dealing with Faker.  I will investigate further on my end.

**Comment by lorisleiva** [comment]
Thanks guys, I've updated the title of the issue so that if other people experience the same problem they can find that thread and help us investigate this.

**Comment by lorisleiva** [comment]
Hey guys, is this still happening with PHP 7.4 or can we close this?
